name: Blur Discord RPC ASI build

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Amax DNS ASI build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      
      - name: Build ASI plugin
        run: |
           cl -I include /D_USRDLL /D_WINDLL /EHcs src/blur_rpc.cpp lib/discord-rpc.lib /MD /link /DLL /OUT:build/blur_rpc.asi
      
      #Temp fix, since upload is broken
      - name: Storing artifact
        uses: actions/upload-artifact@v2
        with:
          name: blur_rpc.asi
          path: build/blur_rpc.asi
          retention-days: 1
          
      - name: Uploading a release
        if: github.ref == 'refs/heads/main'
        uses: "marvinpinto/action-automatic-releases@latest"      
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Testing build"
          files: |
            build/blur_rpc.asi
